services:
  nginx:
    build: ./images/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    networks:
      - rabbit_mq_test_network

  php:
    build: ./images/php
    volumes:
      - ./www:/var/www
    networks:
      - rabbit_mq_test_network

  postgres:
    build: ./images/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./etc/postgres:/etc/postgresql
      - ./logs/postgres:/var/log/postgresql
      - ./postgres:/var/lib/postgresql/data
      - ./data/url_shortener.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rabbit_mq_test_db
    networks:
      - rabbit_mq_test_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbit_mq_test_network

networks:
  rabbit_mq_test_network:
